const GF={exp:new Uint16Array(512),log:new Uint16Array(256),init(){let x=1;for(let i=0;i<255;i++){this.exp[i]=x;this.log[x]=i;x<<=1;if(x&0x100)x^=0x11d}for(let i=255;i<512;i++)this.exp[i]=this.exp[i-255]},mul(a,b){return(!a||!b)?0:this.exp[this.log[a]+this.log[b]]},div(a,b){if(!b)throw Error('0으로 나눌 수 없습니다');if(!a)return 0;return this.exp[(this.log[a]-this.log[b]+255)%255]},pow(a,n){if(!n)return 1;if(!a)return 0;return this.exp[(this.log[a]*n%255+255)%255]}};GF.init();
const poly={mul(p,q){const r=Array(p.length+q.length-1).fill(0);p.forEach((a,i)=>q.forEach((b,j)=>r[i+j]^=GF.mul(a,b)));return r},eval(p,x){return p.reduce((y,c)=>GF.mul(y,x)^c,0)},generator(n){let g=[1];for(let i=0;i<n;i++)g=this.mul(g,[1,GF.exp[i]]);return g},encode(msg,n){const gen=this.generator(n),out=[...msg,...Array(n).fill(0)];for(let i=0;i<msg.length;i++){const coef=out[i];if(coef)for(let j=1;j<gen.length;j++)out[i+j]^=GF.mul(gen[j],coef)}return [...msg,...out.slice(msg.length)]}};
const state={message:[104,105,72,73],nsym:2,errorCount:0,positions:[],magnitudes:[],codeword:[],received:[],syndromes:[],locator:null,found:[],forney:[]};state.codeword=poly.encode(state.message,state.nsym);state.received=[...state.codeword];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const clampByte=v=>Math.max(0,Math.min(255,Number(v)||0));
function setActiveStep(id){$$('.step').forEach(s=>s.classList.toggle('active',s.dataset.target===id))}
function showPanel(id){const panel=$('#'+id);if(!panel)return;panel.scrollIntoView({behavior:'smooth',block:'start'});setActiveStep(id)}
$$('[data-target]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.target)));
const sectionObserver=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActiveStep(visible.target.id)},{rootMargin:'-25% 0px -55% 0px',threshold:[0,.2,.5,.8]});$$('.panel').forEach(p=>sectionObserver.observe(p));
function makeQr(){const root=$('#miniQr');let seed=83;for(let y=0;y<21;y++)for(let x=0;x<21;x++){const e=document.createElement('i'),finder=(x<7&&y<7)||(x>13&&y<7)||(x<7&&y>13);let on;if(finder){const lx=x>13?x-14:x,ly=y>13?y-14:y;on=lx===0||lx===6||ly===0||ly===6||(lx>1&&lx<5&&ly>1&&ly<5)}else{seed=(seed*73+41)%997;on=seed%3===0}if(on)e.className='on';root.append(e)}}
function renderXor(){const a=clampByte($('#xorA').value),b=clampByte($('#xorB').value),r=a^b;$('#xorVisual').innerHTML=`${a.toString(2).padStart(8,'0')}₂&nbsp; (${a})<br>⊕ ${b.toString(2).padStart(8,'0')}₂&nbsp; (${b})<br>────────────<br><b>${r.toString(2).padStart(8,'0')}₂&nbsp; = ${r}</b>`}function renderMul(){const a=clampByte($('#mulA').value),b=clampByte($('#mulB').value),r=GF.mul(a,b);$('#mulVisual').innerHTML=`${a} × ${b} = <b>${r}</b><br><span>다항식 계수의 곱도 GF(256) 안에서 계산</span>`}$('#xorRun').onclick=renderXor;$('#mulRun').onclick=renderMul;
function sampleUnique(count,max){const values=Array.from({length:max},(_,i)=>i);for(let i=values.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values.slice(0,count).sort((a,b)=>a-b)}
function corrupt(){state.errorCount=1+Math.floor(Math.random()*6);state.nsym=state.errorCount*2;state.codeword=poly.encode(state.message,state.nsym);state.positions=sampleUnique(state.errorCount,state.codeword.length);state.magnitudes=state.positions.map(()=>1+Math.floor(Math.random()*255));state.received=[...state.codeword];state.positions.forEach((p,i)=>state.received[p]^=state.magnitudes[i]);state.syndromes=[];state.locator=null;state.found=[];state.forney=[];$('#errorCountLabel').textContent=`${state.errorCount}개`;const n=state.codeword.length;$('#rsStatus').textContent=`RS(${n},4) · ${state.nsym} parity symbols`;$('#syndromeRange').textContent=`α⁰부터 α${superscript(state.nsym-1)}까지`;$('#parityCountText').textContent=`오류 ${state.errorCount}개에 맞춰 패리티와 Syndrome을 각각 ${state.nsym}개 사용합니다.`;$('#chienCount').textContent=n;renderCodeword();renderSyndromes();resetLater()}
function renderCodeword(){const root=$('#codeword');root.innerHTML='';state.received.forEach((v,i)=>{const damaged=state.positions.includes(i),d=document.createElement('div');d.className='symbol'+(damaged?' damaged':'')+(state.found.includes(i)?' found':'');d.innerHTML=`<span>${v}</span><small>#${i}</small>`;root.append(d)});$('#codewordTitle').textContent=`${state.codeword.length}개의 심볼 중 ${state.positions.length}개가 손상됨`;$('#errorState').className='pill warning';$('#errorState').textContent=`${state.positions.length}개 심볼 손상`}
function computeSyndromes(){state.syndromes=Array.from({length:state.nsym},(_,i)=>poly.eval(state.received,GF.exp[i]));renderSyndromes();$('#errorState').className='pill error';$('#errorState').textContent='오류 감지'}function renderSyndromes(){const root=$('#syndromeCells');root.innerHTML='';for(let i=0;i<state.nsym;i++){const val=state.syndromes[i];const d=document.createElement('div');d.className='syndrome-cell'+(val?' nonzero':'');d.style.setProperty('--delay',`${.25+i*.055}s`);d.innerHTML=`<span>S${i+1} = r(α${i?`<sup>${i}</sup>`:'⁰'})</span><strong>${val??'?'}</strong>`;root.append(d)}$('#syndromeConclusion').className='conclusion '+(state.syndromes.length?'':'muted');$('#syndromeConclusion').innerHTML=state.syndromes.length?(state.syndromes.every(v=>v===0)?'<b>오류 없음</b> · 모든 Syndrome이 0입니다.':`<b>오류 존재</b> · ${state.nsym}개 Syndrome으로 오류 ${state.errorCount}개의 위치를 찾습니다.`):'실행 버튼을 눌러 계산 과정을 확인하세요.'}
function berlekampMassey(s){let C=[1],B=[1],L=0,m=1,b=1,steps=[];for(let n=0;n<s.length;n++){let d=s[n];for(let i=1;i<=L;i++)d^=GF.mul(C[i]||0,s[n-i]);steps.push({n,d,L});if(d===0){m++;continue}const T=[...C],coef=GF.div(d,b);while(C.length<B.length+m)C.push(0);for(let j=0;j<B.length;j++)C[j+m]^=GF.mul(coef,B[j]);if(2*L<=n){L=n+1-L;B=T;b=d;m=1}else m++}return{C,L,steps}}
function superscript(n){return String(n).replace(/0/g,'⁰').replace(/1/g,'¹').replace(/2/g,'²').replace(/3/g,'³').replace(/4/g,'⁴').replace(/5/g,'⁵').replace(/6/g,'⁶').replace(/7/g,'⁷').replace(/8/g,'⁸').replace(/9/g,'⁹')}
function runBm(){if(!state.syndromes.length)computeSyndromes();const r=berlekampMassey(state.syndromes);state.locator=r.C;$('#bmSteps').innerHTML=r.steps.map(x=>`<div class="algorithm-line"><b>n=${x.n}</b><span>d = ${x.d} → ${x.d===0?'현재 다항식 유지':'0이 아님 · 다항식 갱신'}</span><span>V=${x.L}</span></div>`).join('');$('#locatorPolynomial').textContent='Λ(x) = '+r.C.map((c,i)=>i===0?c:i===1?`${c}x`:`${c}x${superscript(i)}`).join(' + ');$('#positionResult').className='conclusion muted';$('#positionResult').textContent='위치 방정식 완성 · 이제 각 후보를 대입하세요.';renderChien()}
function renderChien(){const root=$('#chienTrack');root.innerHTML='';for(let p=0;p<state.received.length;p++){const degree=state.received.length-1-p,z=GF.exp[(255-degree)%255],v=state.locator?evalAscending(state.locator,z):null;const d=document.createElement('div');d.className='candidate'+(state.found.includes(p)?' found':'');d.dataset.p=p;d.innerHTML=`BYTE #${p}<br><small>${v===null?'Λ(?)':`Λ=${v}`}</small>`;root.append(d)}}function evalAscending(p,x){let y=0;for(let i=p.length-1;i>=0;i--)y=GF.mul(y,x)^p[i];return y}
async function runChien(){if(!state.locator)runBm();state.found=[];renderChien();for(let p=0;p<state.received.length;p++){const el=$(`.candidate[data-p="${p}"]`);el.classList.add('testing');await new Promise(r=>setTimeout(r,95));const degree=state.received.length-1-p,z=GF.exp[(255-degree)%255];if(evalAscending(state.locator,z)===0){state.found.push(p);el.classList.add('found')}el.classList.remove('testing')}renderCodeword();renderChien();$('#positionResult').className='conclusion';$('#positionResult').innerHTML=state.found.length===state.errorCount?`<b>${state.found.length}개 오류 위치 발견</b><br>${state.found.map(p=>`BYTE #${p}`).join(', ')}`:'오류 위치를 모두 찾지 못했습니다.'}
function forneyMagnitudes(){const v=state.found.length,shifted=state.syndromes.slice(1,v+1),omega=Array(v).fill(0);for(let i=0;i<shifted.length;i++)for(let j=0;j<state.locator.length&&i+j<v;j++)omega[i+j]^=GF.mul(shifted[i],state.locator[j]);const derivative=state.locator.slice(1).map((c,i)=>(i+1)%2?c:0);return state.found.map(p=>{const degree=state.received.length-1-p,X=GF.exp[degree],z=GF.exp[(255-degree)%255],numerator=evalAscending(omega,z),denominator=evalAscending(derivative,z);return{p,E:GF.div(numerator,denominator),numerator,denominator,X}})}
function runForney(){if(!state.locator)runBm();if(!state.found.length){for(let p=0;p<state.received.length;p++){const d=state.received.length-1-p,z=GF.exp[(255-d)%255];if(evalAscending(state.locator,z)===0)state.found.push(p)}}if(!state.found.length)return;state.forney=forneyMagnitudes();$('#forneyResults').innerHTML=state.forney.map((r,i)=>`<div class="magnitude-row"><div class="row-label"><b>오류 ${i+1}</b><span>BYTE #${r.p}</span></div><div class="equation-block"><small>Ω(X${i+1}⁻¹)</small><strong>${r.numerator}</strong></div><i>÷</i><div class="equation-block"><small>Λ′(X${i+1}⁻¹)</small><strong>${r.denominator}</strong></div><i>=</i><div class="equation-block result"><small>Y${i+1}</small><strong>${r.E}</strong></div></div>`).join('');const checks=state.forney.map(r=>({...r,restored:state.received[r.p]^r.E,valid:(state.received[r.p]^r.E)===state.codeword[r.p]}));$('#proofEquation').innerHTML=checks.map(r=>`<span class="proof-line"><b>BYTE #${r.p}</b><span class="restore-before">${state.received[r.p]}</span><i>⊕</i><span>${r.E}</span><i>=</i><strong>${r.restored}</strong></span>`).join('');const passed=checks.length===state.errorCount&&checks.every(r=>r.valid);$('#proofStatus').className='verify-status '+(passed?'success':'failed');$('#proofStatus').innerHTML=passed?`<b>검산 완료</b><span>${checks.length}개 복원 값이 모두 원래 코드워드와 일치합니다.</span>`:'<b>검산 실패</b><span>일부 복원 값이 원래 코드워드와 일치하지 않습니다.</span>';setTimeout(()=>showPanel('verify'),260)}
function resetLater(){state.locator=null;state.found=[];state.forney=[];$('#bmSteps').innerHTML='<p class="muted">Syndrome 계산 후 위치 방정식을 만들 수 있습니다.</p>';$('#locatorPolynomial').textContent='Λ(x) = ?';$('#positionResult').className='conclusion muted';$('#positionResult').textContent='Λ(x)가 만들어지면 위치를 탐색할 수 있습니다.';$('#forneyResults').innerHTML='<article class="card metric placeholder"><span>오류 위치를 찾은 뒤 계산하세요.</span><strong>?</strong><small>Yₖ = Ω(Xₖ⁻¹) / Λ′(Xₖ⁻¹)</small></article>';$('#proofEquation').innerHTML='<span class="proof-empty">4단계에서 오류 크기를 계산하면 검산 결과가 표시됩니다.</span>';$('#proofStatus').className='verify-status muted';$('#proofStatus').textContent='오류 크기 계산을 기다리고 있습니다.';renderChien()}
$('#corruptRun').onclick=corrupt;$('#syndromeRun').onclick=computeSyndromes;$('#bmRun').onclick=runBm;$('#chienRun').onclick=runChien;$('#forneyRun').onclick=runForney;
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('shown');revealObserver.unobserve(entry.target)}}),{threshold:.14,rootMargin:'0px 0px -8%'});$$('.section-head,.panel>.concept-grid,.panel>.lab-grid,.panel>.polynomial,.panel>.sim-layout,.panel>.locator-grid,.panel>.forney-results,.panel>.proof-card,.panel>.verify-status,.panel>.wide,.panel>.restore-card').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--reveal-delay',`${(i%3)*.08}s`);revealObserver.observe(el)});
makeQr();renderXor();renderMul();corrupt();
